### ISSUE TITLE
Fix /category

### ISSUE THREAD

**Issue by aomkirby123** [dusit-thani-core-team/Dusit-Blog#18]
24b300cae79aaebc202b2dfd16537f76e7ad9d31
I believe the /category was fixed long time ago from adding exportPathMap in `next.config.js` and add route to category in `server.js`. But the reason which doesn't work on production is because of built error on now which revert to use lastest success built version. According to now _logs said:
![Error import component/Card](https://user-images.githubusercontent.com/35027979/64481877-7eca2f00-d210-11e9-9e4e-1a57af91bb5f.png)
Which is the lastest commit before this one dc0a36fda78fc203b8ad1f3b77b672ec819f7b8a.
  
I tried chainging the `components/Card` to `components/card` and [redeploy again on my Now account](https://dusithere-45bb0xise.now.sh/category) the result was fantastic:
![image](https://user-images.githubusercontent.com/35027979/64481908-d5d00400-d210-11e9-9ce8-cc53399742fa.png)
I believe that there's a bug with now bot displaying only that the commit was deployed but doesn't display error.

**Comment by wit03** [comment]
Since It was fixed then I'll close the issues
