### ISSUE TITLE
Private Repo

### ISSUE THREAD

**Issue by aomkirby123** [dusit-thani-core-team/Dusit-Blog#19]
Please switch from public to private repo since Contentful API might be exposed to public which might cause an unwanted/malicious intension about the blogging system.

**Comment by wit03** [comment]
@aomkirby123 Since I never pay for GitHub team, I cannot change it to private repository but I'm just considering should we transfer this repo to my GitHub account? So we can change it to private repo.

**Comment by aomkirby123** [comment]
Closed due to Now Secrets is available.
